-- 0001_init: core schema for OpenShop.
-- All identifiers are UUIDs so rows can be generated by any replica without a
-- central sequence, which keeps the system horizontally scalable.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
    id            UUID PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    phone         VARCHAR(32)  NOT NULL DEFAULT '',
    password_hash VARCHAR(255) NOT NULL,
    name          VARCHAR(128) NOT NULL DEFAULT '',
    role          VARCHAR(32)  NOT NULL DEFAULT 'customer',
    status        VARCHAR(32)  NOT NULL DEFAULT 'active',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (lower(email));
CREATE INDEX IF NOT EXISTS idx_users_phone ON users (phone);
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

CREATE TABLE IF NOT EXISTS categories (
    id         UUID PRIMARY KEY,
    name       VARCHAR(128) NOT NULL,
    slug       VARCHAR(160) NOT NULL,
    parent_id  UUID,
    sort       INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_slug ON categories (slug);

CREATE TABLE IF NOT EXISTS products (
    id          UUID PRIMARY KEY,
    category_id UUID,
    title       VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    price_cents BIGINT NOT NULL DEFAULT 0 CHECK (price_cents >= 0),
    currency    VARCHAR(8) NOT NULL DEFAULT 'CNY',
    cover_image VARCHAR(512) NOT NULL DEFAULT '',
    images      JSONB NOT NULL DEFAULT '[]'::jsonb,
    status      VARCHAR(32) NOT NULL DEFAULT 'draft',
    stock       INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_products_slug ON products (slug);
CREATE INDEX IF NOT EXISTS idx_products_category ON products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_status ON products (status);
CREATE INDEX IF NOT EXISTS idx_products_title_trgm ON products (title);

CREATE TABLE IF NOT EXISTS orders (
    id          UUID PRIMARY KEY,
    order_no    VARCHAR(64) NOT NULL,
    user_id     UUID NOT NULL,
    status      VARCHAR(32) NOT NULL,
    currency    VARCHAR(8) NOT NULL,
    total_cents BIGINT NOT NULL CHECK (total_cents >= 0),
    payment_id  UUID,
    expires_at  TIMESTAMPTZ NOT NULL,
    paid_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_order_no ON orders (order_no);
CREATE INDEX IF NOT EXISTS idx_orders_user ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
-- Supports the expiry sweeper efficiently across all replicas.
CREATE INDEX IF NOT EXISTS idx_orders_status_expires ON orders (status, expires_at);

CREATE TABLE IF NOT EXISTS order_items (
    id          UUID PRIMARY KEY,
    order_id    UUID NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id  UUID NOT NULL,
    title       VARCHAR(255) NOT NULL,
    price_cents BIGINT NOT NULL,
    quantity    INTEGER NOT NULL CHECK (quantity > 0),
    subtotal    BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items (order_id);

CREATE TABLE IF NOT EXISTS payments (
    id             UUID PRIMARY KEY,
    order_id       UUID NOT NULL,
    user_id        UUID NOT NULL,
    provider       VARCHAR(64) NOT NULL,
    provider_ref   VARCHAR(128) NOT NULL DEFAULT '',
    amount_cents   BIGINT NOT NULL,
    currency       VARCHAR(8) NOT NULL,
    status         VARCHAR(32) NOT NULL,
    failure_reason VARCHAR(512) NOT NULL DEFAULT '',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_payments_order ON payments (order_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_provider_ref ON payments (provider, provider_ref);
