import { useI18n } from "@lib/i18n";

/**
 * Shows a scannable payment code. WeChat Pay Native hands back a `weixin://`
 * payload instead of a URL, so the storefront renders the QR the API generated
 * rather than navigating anywhere.
 */
export function PaymentQR({ svg, provider }: { svg?: string; provider?: string }) {
  const { t } = useI18n();
  if (!svg) return null;
  return (
    <div className="flex flex-col items-center gap-2 py-4" role="group" aria-label={t("payment.scan")}>
      {/* The SVG is generated by our own API from the provider payload. */}
      <div
        className="size-48 [&>svg]:size-full"
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      <p className="text-muted-foreground text-center text-sm">
        {t("payment.scanWith", { provider: provider ?? "WeChat" })}
      </p>
    </div>
  );
}
